// vim:set filetype=javascript:

// node.js
const mume = require('@shd101wyy/mume')

async function main() {
  await mume.init()

  const engine = new mume.MarkdownEngine({
    filePath: "paper.md",
    config: {
    }
  })

 	// pandoc export
  await engine.pandocExport({runAllCodeChunks: false})

  return process.exit()
}

desc('This is the default task.');
task('default', function (params) {
  main()
});

desc('Watches for changes and runs PDF conversion.');
watchTask('watch', ['default'], function () {
  this.watchFiles.include([
    './*.md'
  ]);
});
